### ISSUE TITLE
Draft: Resolve "Possibility to write GtObjects to GtLogging" - [opened]

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#1062]
In GitLab by @nell_da on Aug 30, 2023, 11:33

_Merges 595-possibility-to-write-gtobjects-to-gtlogging -> master_

## Description

This MR closes #595 

## How Has This Been Tested?

Didn't test it so far.

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

Closes #595

**Comment by jensschmeink** [comment]
See issue #595
