### ISSUE TITLE
Add setting to change logging level at runtime

### ISSUE THREAD

**Issue by mariusalexander** [dlr-gtlab/gtlab-core#1086]
The user should be able to change the logging level - similar to how the verbosity level can be changed on the fly. 

There should also be "Default" option, that uses the logging level as defined by the application

**Comment by jensschmeink** [comment]
The filtering is done in the output dock-widget, isn't it? What would be the benefit of an additional filter?

**Comment by mariusalexander** [comment]
You are correct, however changing the logging level at runtime is not like filtering. It disables the logging for certain levels altogether. 

Say, the logging level is changed to Info Level. Anything below (Debug and Trace) wont be logged at all, even if we change the logging level afterwards. There is no way of retrieving the logging messages sent in between, because none have been sent (at least the ones of certain logging levels). 

Do you see the difference? 

Allowing this change at runtime can speed up certain processes. For example, if you log in a calculator thousands of debug or trace messages and the logging level is set to Trace and above, all logging messages are parsed and written to the different logging destinations. Disabling these levels doe not longer require the processing of the message etc. This can (and will) speed up you code

**Comment by jensschmeink** [comment]
I see the difference. But I think a problem like yours should be solved by verbosity levels. Overall we need a better defined policy how to write logging messages. We do not have any rules how to use the logging levels and verbosity levels.

**Comment by mariusalexander** [comment]
I agree. Using verbosity levels is also less performant than disabling a logging level (at least with the current implementation).
