### ISSUE TITLE
Special characters within PythonTask scripts

### ISSUE THREAD

**Issue by bjoernTWK** [dlr-gtlab/gtlab-core#1125]
If there are special charakters as umlauts or "°" within python-tasks, they are overwritten with "?" or  "�" after project re-opening. The problems occures during the script reading (GtStringProperty).

![image](https://github.com/dlr-gtlab/gtlab-core/assets/158561198/f172fd28-1c54-4343-b8d1-37e8eef19608)

**Comment by rainman110** [comment]
The reason for the bug is, that GTlab reads xml files as UTF-8 but the tasks are stored as ANSI encoding.

To fix this, the tasks should also be stored as UTF-8.
