### ISSUE TITLE
Error creating task group on docker

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#1135]
Starting GTlab comes with the error message

![folder_id (002)](https://github.com/dlr-gtlab/gtlab-core/assets/3213107/87d6d285-299a-4b9d-bb0d-0839201f64cf)

This only happens under docker (linux).

The reason is, that docker does not set the `USER` environment variable.

Hence the default task group should be in this case either "unknown" or "default". @real-ct-ac What would you prefer?

**Comment by real-ct-ac** [comment]
Maybe "undefined"?
