### ISSUE TITLE
GtPropertyStructContainer: Unit and description entries

### ISSUE THREAD

**Issue by bjoernTWK** [dlr-gtlab/gtlab-core#1142]
The usage of properties could be improved, if the user can define a Unit and a description of the container properties. Especially, if several users working on the same project.
![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/158561198/fa954a4e-0fea-426e-ac6e-64b425b93ce6)

**Comment by jensschmeink** [comment]
@bjoernTWK I think that there are no units depends not on the property container in general but it's usage in the python process element you are using. Also an description could be added if it would be of interest there.

**Comment by jensschmeink** [comment]
Reopened in repo of python module
