### ISSUE TITLE
Fix the "Move rows failed" error message when dragging a root task in the process view

### ISSUE THREAD

**Issue by mariusalexander** [dlr-gtlab/gtlab-core#1173]
### Summary

An error (fatal) message "Move rows failed" is triggered when dragging a root task within the process dock

### Expected Behaviour

The error message should neither be a "Fatal" message and it should only trigger if something unexpected happend.

### Reproduction steps

```bash
1. Select a root task
2. Drag it to an empty space in the process view
3. Oberserve the error message (see below)
```

### Screenshots

![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/52258575/58db8113-e99c-4bd0-8e16-76896875a06f)

### GTlab environment

```bash
GTlab Version: 2.0.6-dev
```

### OS

Windows

**Comment by jensschmeink** [comment]
@mariusalexander with the latest changes of #565 the error does not appear anymore. 
But if the task is dropped at another position nothing happens and the order of the tasks stays the same

**Comment by mariusalexander** [comment]
Hm you are right this no longer happens, at least I can reproduce it easily. Still the output is very verbose when performing this action. And the "Fatal" message should at least be refactored to an error, with a more helpful error message.
