### ISSUE TITLE
Add upgrade project command to console application

### ISSUE THREAD

**Issue by OliverKunc** [dlr-gtlab/gtlab-core#1184]
### Summary

If you have many projects, it takes a long time to upgrade each project manually. There should be a possibility to upgrade all at once, with defined settings.

### Improvements

User-friendliness

### Drawbacks

-

Note:
Initial name: Upgrade all projects at once

**Comment by rainman110** [comment]
@OliverKunc Would it be  okay to add this just as an console command?

**Comment by OliverKunc** [comment]
Sure

16.04.2024 16:38:15 Martin Siggel ***@***.***>:

**Comment by jensschmeink** [comment]
Needs feedback from @real-ct-ac

**Comment by jensschmeink** [comment]
Idea: there should be an update command in the console application and then the user could use a bash-script to update more project than one

**Comment by OliverKunc** [comment]
How about the user provides the path to a session.json and then all projects of that session are upgraded?

**Comment by rainman110** [comment]
We want to abandon the multi-project features with GTlab 3.0 which might include the sessions as well (not decided yet).

Hence, we favor an upgrade-command for a single project (from the command line). It is up to you to write a small script that loads the projects from a session to automate the upgrade of multiple projects.

**Comment by OliverKunc** [comment]
That is interesting to know. In that case I would prefer the manual way, as it is today.

IMO this issue can be closed or put on lowest priority.

**Comment by jensschmeink** [comment]
@rainman110 Do you know if this issue is fixed?
