### ISSUE TITLE
🐛 [BUG] - Double Click on open project while task is running leads to warning

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/gtlab-core#1196]
### Summary

If you have a open Project and you double click it in the explorer while a task is running there will be a warning in a dialog

### Expected Behaviour

As the project is the open project no warning should occur

### Reproduction steps

```bash
Open GTlab with a project and open this project.

Start a process which takes a while. 

Double click the projec tin the explorer while the process is running
```

### Screenshots

![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/148551711/946ce4f4-dfc8-47ea-9a23-2f958c599fad)

### GTlab environment

```bash
GTlab Version: 2.0.6
Module 1 Version: X.Y.Z
Module 2 Version: X.Y.Z
```

### OS

Windows

**Comment by rainman110** [comment]
I would even say, that if a task is running, other projects should be greyed out / be inactive instead of showing a warning.

**Comment by NitenIchiry** [comment]
@rainman110 I would in this case disconnect all signals and turn the project dockwidget into the background/unclickable. But I do not really understand how all of this works. I would use `gt::currentProcessExecutor().taskCurrentlyRunning()` to check whether a task is running, but at what point can I access the widgets and diasble them ? Is there a loop for the execution ? This should work with a signal slot in the app, shouldnt it ?

**Comment by rainman110** [comment]
@NitenIchiry Without having had a look into the code. I would not disconnect any signals though. There is a `QSignalBlocker` object that you can use to temporarily disable passing signals .

I would though check in the code, where the warning message widget is created, to only generate it, if a task is running and if the project is not the current project. Let me find out, where the message box is generated...

**Comment by rainman110** [comment]
@NitenIchiry Please see here: 

https://github.com/dlr-gtlab/gtlab-core/blob/4fdcad7be02f2d32f5d8a079066f761703d8197f/src/gui/object_ui/gt_projectui.cpp#L350-L364

You simply need to add a check, whether the current project is not the one to switch
