### ISSUE TITLE
[CHANGE] - Replace use of QValidator by own class

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#1209]
### Summary

The dataprocessor and core are using the QValidator class to validate string properties with mainly regexps.

Since QValidator is a QtGui class, this should be replace by an own implementation.

To be discussed:
 - Do we need a Validator interface or are regexps enough?
 - Do we need to mimic the QtValidator interface to keep API changes small?

### Impact on the codebase

Relatively small in GTlab Core, but modules might be effected, if they are using custom validators.

### Current workarounds

-

**Comment by jensschmeink** [comment]
Add free function to GTlab GUI to convert GtValidator to QValidator
