### ISSUE TITLE
💡 [REQUEST] - Interface to add Icons to the icon browser via modules

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/gtlab-core#1225]
### Summary

Origin of the Issue is here (https://gitlab.dlr.de/gtlab/gtlab-issuetracking/-/issues/53).

The idea is to have the option to add module specific icons to the icon browser

### Improvements

Deveolpers of this module and of modules that link to this module have a better overview of existing icon definitions to reuse them and so improve the consistant look and feel of GTlab

### Drawbacks

There seems to be the need of some kind of new interface. Additionally the icon browser might be overcrowded

### Current workarounds

Currently module specific icons are part of the core or might not be seen in the icon brwoser but only in the directory structure of the repository

**Comment by jensschmeink** [comment]
@mariusalexander do you think what would be the effort and the needs (especially concerning the interfaces) to work on this? Is it worth it (I dont think so ;) ). Shall we keep it or close it?

**Comment by rainman110** [comment]
Just my two cents here: I am not sure, whether it makes sense to provide an interface. Either use the icons provided by the core or use your own ones. You should not rely on icons from third parties IMHO, as they could also change by time.

**Comment by rainman110** [comment]
If anyone likes to integrate icons, one can simply create a short MR and thats it then.

**Comment by mariusalexander** [comment]
@jensschmeink @rainman110  I agree, with both of you. It is probably not worth it (after all, it is a dev-only widget). It would be mostly for convenience. IMO we could close this and if it's needed or one has time to spare he/she could reopen the issue and implement it.
