### ISSUE TITLE
[CHANGE] - Run function of GtTask is unused

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/gtlab-core#1232]
### Summary

The function _run()_ of GtTask seems not to be used. 
Maybe it should be checked if it is needed for the RPU or else should be removed to make the interface clearer

### Impact on the codebase

Possible usage hat to be checked as it needs to be kept if it is used

**Comment by mariusalexander** [comment]
> do you know if you use the run function for the RPU?

I dont't think so, it should use the Core-Process-Executor
