### ISSUE TITLE
🐛 [BUG] - GTlab crashes when two tasks are deleted

### ISSUE THREAD

**Issue by Patrick-Wehrel** [dlr-gtlab/gtlab-core#1266]
### Summary

GTlab crashes when two skipped tasks are deleted. For example:

![grafik](https://github.com/user-attachments/assets/8cbb9af0-f966-49b7-9684-5caca34630ae)

EDIT: I also observe this behavior when deleting all tasks, regardless they are skipped or not.

### Expected Behaviour

GTlab should not crash when deleting two or more tasks

### Reproduction steps

```bash
1. Go to Tasks
2. Create multiple tasks and skip them
3. Delete more than one skipped task
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### GTlab environment

```bash
GTlab Version: 2.0.9
```

### OS

Windows

**Comment by rainman110** [comment]
Thanks @Patrick-Wehrel for posting the issue. 

I think it belongs to the changes from MR #1168. This MR introduced a variety of bugs, including your recently posted bug https://github.com/dlr-gtlab/gtlab-core/issues/1258#issuecomment-2219903488. 

We decided to revert it for now, which will also mean, that it is impossible to select and delete and move multiple process elements. What do you think?

**Comment by Patrick-Wehrel** [comment]
@rainman110 Thanks for caring :) Sounds good to me. The new functions regarding multiple process elements are not so important for me.

**Comment by rainman110** [comment]
A quick analysis check show, that this issue also appeared with GTlab 2.0.6, i.e. before the changes to the process editor.

Interestingly, selecting 2 process elements and pressing "del" key works, but using "delete" from the context menu results in a crash.

**Comment by rainman110** [comment]
Okay, I found the guilty commit 51d7b59edaddf2cfb4854ab5. @mariusalexander  I am looking at you kid 😏 

The commit fortunately is quite moderate.

**Comment by rainman110** [comment]
Okay, it seems I found the line creating the problem:

**Comment by jensschmeink** [comment]
done

**Comment by mariusalexander** [comment]
upsy daisy 👀
