### ISSUE TITLE
💡 [REQUEST] - Copy Value of Read-only Property

### ISSUE THREAD

**Issue by OliverKunc** [dlr-gtlab/gtlab-core#1267]
### Summary

ATM there is no way for the user to copy the value of a read-only property, other than manual typing. It would be handy if it was possible to copy the values of read-only `GtIntProperty`, `GtDoubleProperty`, `GtStringProperty`, ... to the clipboard.

Possible implementations:
- a context menu that's only there in read-only mode
- make the value selectable (so that there is the standard context menu of the OS or ctrl+c)
- add a "copy" button to the end of the line. This button would handily be there only in read-only mode because in non-read-only mode the user can use the context menu of the OS or ctrl+c.

### Improvements

Access values in a processable way. I.e. the user can not just visually inspect the value but also use it elsewhere, e.g. copy numerical values to text files or copy folder paths to file explorers or command lines.

### Drawbacks

The "copy" button would take up space. I can't think of drawbacks of the other suggested solutions.

**Comment by jensschmeink** [comment]
It seems to work with Ctrl+C to copy the entry of a read only property
@OliverKunc please verify

**Comment by jensschmeink** [comment]
> I can confirm Ctrl+C works. Thanks for the hint.

@OliverKunc would this be sufficient to close the issue? Or what is important for you what still needs a change?

**Comment by OliverKunc** [comment]
I think it is not obvious that Select + Ctrl + C works because there is neither a context menu (right-click menu) nor any feedback for successful copy.

Is it possible to implement a very simple context menu with just a "Copy (Ctrl + C)" option? If not or not with reasonable effort, this issue may be closed.

In any case, it should be mentioned in the documentation.

**Comment by jensschmeink** [comment]
The pull request #1300 added a basic context menu an so should fix this issue
