### ISSUE TITLE
Comma or Point

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#134]
In GitLab by @bjoernTWK on Jul 21, 2021, 08:53

## Summary
Currently, not in every input area the same symbole must be used to separate digitals. In the main cases a point is used but in widgets the "windows"-setting is used (in my case a comma).

## What is the current bug behavior?
Mixed digital separator (comma and point)

## What is the expected correct behavior?
In every case the same separator should be used.

## Relevant logs and/or screenshots

![image](https://my-gitlab-bucket.s3.amazonaws.com/727352741/5f64f0a219b870b15850ef25f1d14f1c1025b33e3a19d51451f53c6b034d4c02/image.png)

**Comment by jensschmeink** [comment]
After the latest update of basic tools the last known occurrence of comma separated values is removed. If there are more widgets using commas these should be fixed in separate issues
