### ISSUE TITLE
Modify sub-sub-properties in a calculators wizard

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#191]
In GitLab by @goer_ax on Feb 4, 2022, 13:33

## Summary
If you open a calculators wizard and modify a sub-sub-property, the calculator does not take over the changes after closing the wizard. This is only a problem if you use the wizard. Changing a sub-sub-property in the "Properties"-window is not a problem.

## Steps to reproduce
This error appeared while using the GtpRegTestAdaptCalculator. Open the wizard and select "Overwrite Specific Gold Files" as Mode. The following string "Test Result XML File Name" will not be taken over after the wizard is closed. 

## Possible fixes

**Comment by rainman110** [comment]
@jensschmeink could this also be a order of registration thing?

**Comment by jensschmeink** [comment]
> @jensschmeink could this also be a order of registration thing?

I'm not sure but I cannot reproduce the problem mentioned in the issue. So I'll close the issue
