### ISSUE TITLE
CI: Devtool update job fails, if no update available

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#240]
In GitLab by @rainman110 on Jun 10, 2022, 12:18

Currently, the job fails, if there are no updates. Since this job may fail, this no no problem for the pipeline.

There's however still a warning. IMHO, if no updates are available, this should not be seen as an error or a warning.

**Comment by jensschmeink** [comment]
@rainman110 is this still relevant in our docker pipelines?

**Comment by rainman110** [comment]
No. Is fixed
