### ISSUE TITLE
Make GtpPerfTableSelectionProperty abstract for all GtObjects

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#30]
In GitLab by @view_ma on Feb 20, 2020, 14:45

The functionality of the GtpPerfTableSelectionProperty within the OP calculator should be made available for any (or client specific) Object to enable simplified selection of e.g. GtdComponent's and GtpModule's from within sketchpad calulators. Will be used definitely for all simple engine sketcher calculators and others.

Mantis Datum: 	25-09-18 09:19

**Comment by jensschmeink** [comment]
Use case is not clearly given anymore
