### ISSUE TITLE
Revisit and cleanup logging statements

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#354]
In GitLab by @mariusalexander on Nov 29, 2022, 14:07

Since we have updated our logging system, we should revisit our logging statements and cleanup/fix bad formatted messages etc.

**Comment by mariusalexander** [comment]
I would assume this is a duplicate (see #1085). Should we close this issue then? @jensschmeink @rainman110

**Comment by jensschmeink** [comment]
Ok. I closed this
