### ISSUE TITLE
Project with Umlaut in file path could not be opened

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#45]
In GitLab by @bjoernTWK on Feb 25, 2020, 14:09

## Summary
If the user set a file path that includes umlauts the property is working correctly until the project is reopened.

## Steps to reproduce

> How can we reproduce the issue - this is very important!
1. Set a path with umlaut in a file path property (e.g. GtOpenFileNameProperty)
2. Save the project
3. Reopen the project (umlauts are replacced with �)

## What is the current bug behavior?
refill umlauts with �

## What is the expected correct behavior?
restore the correct path

**Comment by rainman110** [comment]
I cannot reproduce the issue anymore with the current master. I suggest to close the issue. I will add a file path property to the testing module anyhow to be able to check this.

**Comment by rainman110** [comment]
@bjoernTWK Can you please check, if this issue is fixed with *YOUR* latest GTlab version 2.0.6?

**Comment by bjoernTWK** [comment]
@rainman110 In the latest released version I can still reproduce the issue
![image](https://github.com/dlr-gtlab/gtlab-core/assets/158561198/f2aef592-a38f-435b-81aa-163ac61296a9)
![image](https://github.com/dlr-gtlab/gtlab-core/assets/158561198/dd5cc7ee-6f67-4646-9f01-990931c56049)

(in this case the folder was named "ÄÄÄ")

**Comment by bjoernTWK** [comment]
Maybe this is related to https://github.com/dlr-gtlab/gtlab-core/issues/1125#issuecomment-2045254647

**Comment by rainman110** [comment]
> Maybe this is related to [#1125 (comment)](https://github.com/dlr-gtlab/gtlab-core/issues/1125#issuecomment-2045254647)

Probably not, since the version I am using locally does not contain yet this fix. But probably it is the same reason, why the encoding is misinterpreted.

**Comment by rainman110** [comment]
Okay, the problem only happens in tasks and calculators. I just had a call with @bjoernTWK , the problem is fixed with PR #1169.
