### ISSUE TITLE
Connection of signal of changed theme and slot of mdi items does not seem to work

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#503]
In GitLab by @jensschmeink on Mar 28, 2023, 15:31

In the mdi launcher the app and the mdiitems are connected to react on the change of the theme:
  
    connect(gtApp, SIGNAL(themeChanged(bool)), mdiItem,  
            SLOT(onThemeChanged()));    

But the slot is not triggered if the theme is changed. I think it worked before. I'm not sure why this is not working anymore.

**Comment by mariusalexander** [comment]
@rainman110 This is an old issue, but I gave it a quick test, it seems that the slot `onThemeChanged` is called.

**Comment by rainman110** [comment]
I think, @jensschmeink posted the issue originally. Should we close it?

**Comment by jensschmeink** [comment]
> I think, @jensschmeink posted the issue originally. Should we close it?

As @mariusalexander tested it succesfully we can close it
