### ISSUE TITLE
Logging too many messages in a short time period will freeze GTlab for an extended period

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#531]
In GitLab by @schn_bo on Apr 24, 2023, 07:27

## Summary
If a Python task is executed in which many exceptions are thrown, the error widget freeze and aftwards the whole GTlab-instance.

## Steps to reproduce

> How can we reproduce the issue - this is very important!
Create a task in which a greate number of exceptions are thrown (in my case the number is much higher than a thousend msg).

## What is the current bug behavior?
The GTlab-Widget freeze and the process is not proceeding any more. 

## What is the expected correct behavior?
The exception should be summeriazed and shown without any interruption of processes and program crash.

## Relevant logs and/or screenshots
![grafik](https://my-gitlab-bucket.s3.amazonaws.com/727352741/6f594471286b9860a281d03438b3393e4e6a7511c0d42adf2262ddbf8f8d4cdb/grafik.png)
> Paste any relevant logs - please use code blocks (```) to format console output,
> logs, and code as it's very hard to read otherwise.)

## Possible fixes

> If you can, link to the line of code that might be responsible for the problem.

**Comment by jensschmeink** [comment]
@mariusalexander I cannot find the branch anymore. Is this done? Can the issue be closed?

**Comment by mariusalexander** [comment]
I will close this issue once the error widget was removed.
