### ISSUE TITLE
GTlab Crash: deleting datamodel-object in calculator.run() and sub-datamodel-objects are unfolded in model view

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#56]
In GitLab by jannik on Mar 26, 2020, 11:06

Case: An object should be replaced by a calculator (Example: Knowledge-Based Sketching Task should overwirte assembly)

How: Therefore the object is deleted in the run-method of the calculator and a new object is created keeping the uuid and inserting it at the postion of the deleted object. Works fine, no problems or crashes apart from ...

Problem: If the datamodel viewer is unfolded to a certain degree (Example: Knowledge-Based Sketching Task should overwirte assembly -> assembly is unfolded until the radial-profile node of a blade row) and the calculator successfully finished, GTlab crashes ...

**Comment by jensschmeink** [comment]
The problem can curently not be reproduced
