### ISSUE TITLE
GtPropertyModel uses a project wides scope when creating undo/redo commands

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#568]
In GitLab by @mariusalexander on Jul 4, 2023, 13:22

In GtPropertyModel there are a few usages where a project wide undo/redo command is created. I have not looked at this in more detail, ut I would imagine that a project wide scope is not needed here (I might not be possible to use another scope without many ABI/API changes though)

**Comment by rainman110** [comment]
A first testing allows to simply use `m_scope` in the property model instead of the project.

**Comment by mariusalexander** [comment]
> @mariusalexander It is limited to modifying the property containers. Is this what you mean?
> 
> There are also many other locations, where the whole project scope is used for making a command. As there any reason, why you picked out the property model and not the other locations?

I have had a look  at the use cases and indeed, the project is used in many instances where it should not be used IMO. I will create a few more issues
