### ISSUE TITLE
Possibility to write GtObjects to GtLogging

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#595]
In GitLab by @NelDav on Aug 30, 2023, 11:24

Currently, GtObject cannot be written into the GtLogging Stream by default.
For debugging purpose, it would be nice to offer a default representation of a GtObject when trying to print it with GtLogging.

Therefore, we can use Stream insertion.
I suggest a presentation like this, wehre the Class name and all GtProperties of this class are shown:

```
DEBUG [13:12:49] PredictDataSpoolStageBladeRowInOutletAbsoluteSystem ( 
	 TemperatureTotal = 677.0128287860277 
	 PressureTotal = 63175.183992146965 
	 EnthalpyTotalMixed = 427224.4682865617 
	 EnthalpyTotal = 427224.4682865617 
	 MachNumber = 0.6613897392208912 
	 Velocity = 326.65600362436 
	 VelocityTangential = -262.6792483365404 
	 VelocityAxial = 194.17455342342882 
	 AngleFlow = -0.9342380705993836 
	 TemperatureTotalCoolDP = 677.0015932180852 
	 PressureTotalCoolDP = 0 )
```

The code producing this would look like this:

```c++
class PredictDataSpoolStageBladeRowInOutletAbsoluteSystem : public GtObject {
    GtDoubleProperty m_temperatureTotal("TemperatureTotal", "name", ...);
    ...
};

PredictDataSpoolStageBladeRowInOutletAbsoluteSystem system;

gtDebug() << system;
```

To support this, we need to implement the followin function into `gtobject.h`:

```c++
gt::log::Stream&
operator<<(gt::log::Stream& os, const GtObject& obj)
{
    const QString className = obj.staticMetaObject.className();

    os << className << "(";

    for (const GtAbstractProperty* property : obj.properties())
    {
        os << "\n\t" << property->ident() << "=" << property->valueToVariant().toString();
    }

    os << ")";

    return os;
}
```

**Comment by jensschmeink** [comment]
Number of children would be an interesting entry, too.

**Comment by jensschmeink** [comment]
Should be discussed in larger group where author is part of.

**Comment by jensschmeink** [comment]
@NelDav what is the current use case? A general print of all properties seems not to be sense full in general

**Comment by NelDav** [comment]
The use case is to print the current state of an object into the log.
A log becomes handy, when an issue occurs. On most cases, an issue occurs if an object has a specific state. 
For example, is one property of the object is a nullpointer or if a certain property has an specific value.
To detect such cases, it is useful to print the state of an object into the log.
In GTlab, the state of an object is mostly defined by the properties of this object. Because of that, I think that it is useful to simply print all properties as standard behavior of `GtObject`. You can still implement special behavior for certain objects by overriding the left shift operator for those objects.

**Comment by rainman110** [comment]
IMHO, it really depends on the situation what you want to see and for which reason you are printing it to the log.

 - For debugging purposes, it might become useful to see all property values
 - You could also just want to see the object name and the type
 - Or the parent / child structure
 - Or the memory it is using
 - Or thousand other things

Hence, it depends on the use case and I don't want to pollute the log with property values, if i am not interested in them.

We could though think of a helper class or a log modifier, to tweak, what information is printed, similar to `std::setprecision(2);`

**Comment by rainman110** [comment]
So here's my suggesion:

 - Provide a steam operator to print the object name + type
  
    DEBUG [13:12:49]  Object: "PreDesign" (GtdPredesign)
   
Provide helper function `propToDbgStr(const GtObject&) -> str::string ` that return a json string, which then can be used for logging, i.e.

```

gtDebug() << propToDbgStr(&predesign);

DEBUG [13:12:49] AbsoluteSytem = { 
	 "TemperatureTotal": 677.0128287860277,
	 "PressureTotal":  63175.183992146965,
	 "EnthalpyTotalMixed": 427224.4682865617
}
```

**Comment by NelDav** [comment]
I think `gtDebug() << &obj;` should print the address, as it is the case right now. (I think it is) But in general, I like the idea.
