### ISSUE TITLE
Property Struct Container does not support hidden members or other flags (e.g read only)

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#602]
In GitLab by @mariusalexander on Sep 26, 2023, 10:06

The graphical representation of property struct containers does not hide properties, that have the `isHidden` flag activated. This could be useful for properties that the user should not see or alter or that are for internal use only. I @mariusalexander have tested this by using the `gt::makeHidden` property function decorator.

This issue is linked to #584

**Comment by jensschmeink** [comment]
Like originally posted in #584:
Similar to a basic GtAbstractProperty one might want to create a property struct container, that cannot be viewed using the property dock (for example just to store dynamic data, that is not of interest for the user). Additionally one might want to create a read-only container, i.e. a container, that cannot be altered by the user.

**Comment by rainman110** [comment]
@mariusalexander  & @jensschmeink What is the use case of a read-only container? Wouldn't you then just use plain properties instead?

**Comment by rainman110** [comment]
@mariusalexander But I still see no use case. I completely read only container is useless from the users point of view. In this case, a hidden container can be used. Why show something to the user, when he has no way to change it?

There's also to possibility to add read-only properties into a fixed-size container, making in completely read-only

**Comment by mariusalexander** [comment]
Okay I see your point. It has little benefit. But then I like the system you have implemented, where the size is "read-only"

**Comment by rainman110** [comment]
@jensschmeink As discussed with you, we move this new feature to 2.1.0
