### ISSUE TITLE
GtEnumProperty::setValueFromVariant should fail in case the variant is not a valid enum value.

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#609]
In GitLab by @NelDav on Oct 27, 2023, 08:06

Regarding PrEDiCT, we discussed the following:

> > Currently PrEDiCT defaults to `Grieb` if the specified cooling model isn't found. This is the desired behaviour and adding an upgrade task for this would be redundant.
> 
> Completely right. But it might be bad, if this implicit conversion is done silently. I suggest, that we create a warning. However, so far we cannot recognize if a implicit conversion was done or not.
> 
> I suggest the following procedure:
> 
> 1. `setValueFromVariant` should not override the current value of the `GtEnumProperty` in case the value cannot be converted into an enum value.
> 1. `setValueFromVariant` will return `false` in such cases.
> 1. The IO-Handler already creates a warning in case the `setValueFromVariant` function returns `false`.

I think in most circumstances, it would be better to not change the value of `GtEnumProperty` if it is impossible to convert the String, stored in the variant, into an enum.

**Comment by jensschmeink** [comment]
Discuss with david
