### ISSUE TITLE
Tile Windows in GTlab 2.0

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#610]
In GitLab by @schn_bo on Nov 6, 2023, 10:35

## What is the purpose of the change?
In many processes (especially in perforamnce computation) the tile windows in the GTlab 1.7 improves the work.
- Fast compare of different result tables
- look at model editor during the filter editing in results 

## Which tasks have to be performed?
- [ ] it would be great, if different windows could be shown next to each others

**Comment by rainman110** [comment]
Since moving away from the MDI layout, tiling the screen is not as simple to implement anymore.
IMHO, we should not implement this right now, as it requires a larger refactoring with only a small benefit. 

@real-ct-ac What do you think?

**Comment by real-ct-ac** [comment]
I also think that it won't be easy to implement. We should rather think about "undocking" the MdiItems.

**Comment by jensschmeink** [comment]
Will be solved as #604
